services:
  postgres-dev:
    image: postgres:16
    container_name: bank-postgres-dev
    environment:
      POSTGRES_DB: ${DB_DEV_NAME}
      POSTGRES_USER: ${DB_DEV_USER}
      POSTGRES_PASSWORD: ${DB_DEV_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - bank_pg_data_dev:/var/lib/postgresql/data

volumes:
  bank_pg_data_dev: